version: "3.4"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - combined-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applications_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - combined-network

  react_app:
    build: ./react_app
    container_name: react_app
    networks:
      - combined-network

  nest_api:
    build: ./nest_api
    container_name: nest_api
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge